### PR TITLE
[BC] Float discount & other fixes

### LINKED ISSUE #6: Update README
The readme is very much out of date

### LINKED ISSUE #24: Unable to run command due to (I guess) wrong condition
```
bin/console setono:sylius-catalog-promotion:process -vvv
Did not do nutting <-----------
```

### PR DESCRIPTION
**Pull request by igormukhingmailcom**
Updated: README.md (fixes #6)
Fixes: #2
Added: Better description when nothin to process (fixes #24)
Added: Useful `hasDiscount`, `getDiscountAmount`, `getDisplayableDiscount` to `ChannelPricingTrait`
Updated: Discount field to accept float values
Improved: Promo fixtures to be overwritable
Improved: PromotionRuleFactory to be able to create custom rules (not hardcoded ones)
Fixed: Analyser warnings at behat tests
Fixed: Plugin renaming artifacts
Removed: AppBundle
Removed: WebServerBundle

### CODE REVIEW

File: src/Command/ProcessPromotionsCommand.php [hunk 1]
```diff
@@ -77,20 +78,16 @@ protected function configure(): void
...
 
             return 0;
         }
 
-        $force = is_bool($input->getOption('force')) ? $input->getOption('force') : false;
-
-        $lastExecution = $this->getLastExecution();
-
+        /** @var bool $force */
+        $force = $input->getOption('force');
```
Comment (loevgaard) [inline src/Command/ProcessPromotionsCommand.php:90]: 👍

**Review by loevgaard — APPROVED** [review]
